site_name: ml-assert
repo_url: https://github.com/heyshinde/ml-assert
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - content.tabs.link
  palette:
    # Palette toggle for light vs dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/heyshinde/ml-assert
copyright: Copyright &copy; 2025 Shinde Aditya
docs_dir: source
nav:
  - 'Home': 'index.md'
  - 'User Guide':
    - 'Data Assertions': 'data_assertions.md'
    - 'Statistical Assertions': 'statistical_assertions.md'
    - 'Model Performance': 'model_assertions.md'
    - 'Fairness & Explainability': 'fairness.md'
    - 'Integrations': 'integrations.md'
    - 'Plugins': 'plugins.md'
    - 'Explainability': 'explainability.md'
  - 'API Reference':
    - 'Core API': 'api/core.md'
    - 'Data API': 'api/data.md'
    - 'Model API': 'api/model.md'
    - 'Stats API': 'api/stats.md'
    - 'Fairness API': 'api/fairness.md'
    - 'Integrations API': 'api/integrations.md'
    - 'Plugins API': 'api/plugins.md'
